### ISSUE TITLE
phmapply -- get sample

### ISSUE THREAD

**Issue by b1quint** [b1quint/samfp-tools#22]
SAM-FP Tools: PHase-Map Apply
    by Bruno Quint (bquint@ctio.noao.edu)
    version v0.7.0 2017-9
    Starting program.
    
    Root dir: 
    Cube to be corrected: standard_output.fits
    Phase-map to be applied: standard_output--fit_phmap.fits
    Output corrected cube: phc_standard_output.fits
    
    Emitted/systemic wavelength: 6600.00 A
    Systemic velocity: 0.00 km/s
    Observed wavelength: 6600.00 A
    
    Reading cube to be corrected.
    Done.
    Reading phase-map to be applied.
    Done.
Traceback (most recent call last):
  File "/home/bquint/anaconda2/envs/astroconda/bin/phmapply", line 6, in <module>
    samfp.phmapply.main()
  File "/home/bquint/anaconda2/envs/astroconda/lib/python2.7/site-packages/samfp/phmapply.py", line 134, in main
    sample = float(data_cube.header['CDELT3'])
  File "/home/bquint/anaconda2/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 150, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/bquint/anaconda2/envs/astroconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1675, in _cardindex
    raise KeyError("Keyword {!r} not found.".format(keyword))
KeyError: "Keyword 'CDELT3' not found."

**Comment by b1quint** [comment]
created a temporary solution. Need to fix.
